local ship_1f_w_stairs = DoorSlot("ship", "1f_w_stairs")
local ship_1f_w_stairs_hub = DoorSlotHub("ship", "1f_w_stairs", ship_1f_w_stairs)
ship_1f_w_stairs:setHubIcon(ship_1f_w_stairs_hub)
local ship_1f_w_entrance = DoorSlot("ship", "1f_w_entrance")
local ship_1f_w_entrance_hub = DoorSlotHub("ship", "1f_w_entrance", ship_1f_w_entrance)
ship_1f_w_entrance:setHubIcon(ship_1f_w_entrance_hub)
local ship_1f_w_room_s = DoorSlot("ship", "1f_w_room_s")
local ship_1f_w_room_s_hub = DoorSlotHub("ship", "1f_w_room_s", ship_1f_w_room_s)
ship_1f_w_room_s:setHubIcon(ship_1f_w_room_s_hub)
local ship_1f_w_room_n = DoorSlot("ship", "1f_w_room_n")
local ship_1f_w_room_n_hub = DoorSlotHub("ship", "1f_w_room_n", ship_1f_w_room_n)
ship_1f_w_room_n:setHubIcon(ship_1f_w_room_n_hub)
local ship_1f_e_stairs = DoorSlot("ship", "1f_e_stairs")
local ship_1f_e_stairs_hub = DoorSlotHub("ship", "1f_e_stairs", ship_1f_e_stairs)
ship_1f_e_stairs:setHubIcon(ship_1f_e_stairs_hub)
local ship_1f_e_entrance = DoorSlot("ship", "1f_e_entrance")
local ship_1f_e_entrance_hub = DoorSlotHub("ship", "1f_e_entrance", ship_1f_e_entrance)
ship_1f_e_entrance:setHubIcon(ship_1f_e_entrance_hub)
local ship_1f_e_room_sw = DoorSlot("ship", "1f_e_room_sw")
local ship_1f_e_room_sw_hub = DoorSlotHub("ship", "1f_e_room_sw", ship_1f_e_room_sw)
ship_1f_e_room_sw:setHubIcon(ship_1f_e_room_sw_hub)
local ship_1f_e_room_se = DoorSlot("ship", "1f_e_room_se")
local ship_1f_e_room_se_hub = DoorSlotHub("ship", "1f_e_room_se", ship_1f_e_room_se)
ship_1f_e_room_se:setHubIcon(ship_1f_e_room_se_hub)
local ship_1f_e_room_nw = DoorSlot("ship", "1f_e_room_nw")
local ship_1f_e_room_nw_hub = DoorSlotHub("ship", "1f_e_room_nw", ship_1f_e_room_nw)
ship_1f_e_room_nw:setHubIcon(ship_1f_e_room_nw_hub)
local ship_1f_e_room_ne = DoorSlot("ship", "1f_e_room_ne")
local ship_1f_e_room_ne_hub = DoorSlotHub("ship", "1f_e_room_ne", ship_1f_e_room_ne)
ship_1f_e_room_ne:setHubIcon(ship_1f_e_room_ne_hub)
local ship_b1f_stairs_w = DoorSlot("ship", "b1f_stairs_w")
local ship_b1f_stairs_w_hub = DoorSlotHub("ship", "b1f_stairs_w", ship_b1f_stairs_w)
ship_b1f_stairs_w:setHubIcon(ship_b1f_stairs_w_hub)
local ship_b1f_stairs_e = DoorSlot("ship", "b1f_stairs_e")
local ship_b1f_stairs_e_hub = DoorSlotHub("ship", "b1f_stairs_e", ship_b1f_stairs_e)
ship_b1f_stairs_e:setHubIcon(ship_b1f_stairs_e_hub)
local ship_b1f_room_nw = DoorSlot("ship", "b1f_room_nw")
local ship_b1f_room_nw_hub = DoorSlotHub("ship", "b1f_room_nw", ship_b1f_room_nw)
ship_b1f_room_nw:setHubIcon(ship_b1f_room_nw_hub)
local ship_b1f_room_n = DoorSlot("ship", "b1f_room_n")
local ship_b1f_room_n_hub = DoorSlotHub("ship", "b1f_room_n", ship_b1f_room_n)
ship_b1f_room_n:setHubIcon(ship_b1f_room_n_hub)
local ship_b1f_room_ne = DoorSlot("ship", "b1f_room_ne")
local ship_b1f_room_ne_hub = DoorSlotHub("ship", "b1f_room_ne", ship_b1f_room_ne)
ship_b1f_room_ne:setHubIcon(ship_b1f_room_ne_hub)
local ship_b1f_room_sw = DoorSlot("ship", "b1f_room_sw")
local ship_b1f_room_sw_hub = DoorSlotHub("ship", "b1f_room_sw", ship_b1f_room_sw)
ship_b1f_room_sw:setHubIcon(ship_b1f_room_sw_hub)
local ship_b1f_room_s = DoorSlot("ship", "b1f_room_s")
local ship_b1f_room_s_hub = DoorSlotHub("ship", "b1f_room_s", ship_b1f_room_s)
ship_b1f_room_s:setHubIcon(ship_b1f_room_s_hub)
local ship_b1f_room_se = DoorSlot("ship", "b1f_room_se")
local ship_b1f_room_se_hub = DoorSlotHub("ship", "b1f_room_se", ship_b1f_room_se)
ship_b1f_room_se:setHubIcon(ship_b1f_room_se_hub)
local ship_rooms_ne = DoorSlot("ship", "rooms_ne")
local ship_rooms_ne_hub = DoorSlotHub("ship", "rooms_ne", ship_rooms_ne)
ship_rooms_ne:setHubIcon(ship_rooms_ne_hub)
local ship_rooms_sw = DoorSlot("ship", "rooms_sw")
local ship_rooms_sw_hub = DoorSlotHub("ship", "rooms_sw", ship_rooms_sw)
ship_rooms_sw:setHubIcon(ship_rooms_sw_hub)
local ship_rooms_se = DoorSlot("ship", "rooms_se")
local ship_rooms_se_hub = DoorSlotHub("ship", "rooms_se", ship_rooms_se)
ship_rooms_se:setHubIcon(ship_rooms_se_hub)