local aqua_hideout_motor_stairs = DoorSlot("aqua_hideout", "motor_stairs")
local aqua_hideout_motor_stairs_hub = DoorSlotHub("aqua_hideout", "motor_stairs", aqua_hideout_motor_stairs)
aqua_hideout_motor_stairs:setHubIcon(aqua_hideout_motor_stairs_hub)
local aqua_hideout_motor_w = DoorSlot("aqua_hideout", "motor_w")
local aqua_hideout_motor_w_hub = DoorSlotHub("aqua_hideout", "motor_w", aqua_hideout_motor_w)
aqua_hideout_motor_w:setHubIcon(aqua_hideout_motor_w_hub)
local aqua_hideout_motor_e = DoorSlot("aqua_hideout", "motor_e")
local aqua_hideout_motor_e_hub = DoorSlotHub("aqua_hideout", "motor_e", aqua_hideout_motor_e)
aqua_hideout_motor_e:setHubIcon(aqua_hideout_motor_e_hub)
local aqua_hideout_storage_stairs = DoorSlot("aqua_hideout", "storage_stairs")
local aqua_hideout_storage_stairs_hub = DoorSlotHub("aqua_hideout", "storage_stairs", aqua_hideout_storage_stairs)
aqua_hideout_storage_stairs:setHubIcon(aqua_hideout_storage_stairs_hub)
local aqua_hideout_storage_w = DoorSlot("aqua_hideout", "storage_w")
local aqua_hideout_storage_w_hub = DoorSlotHub("aqua_hideout", "storage_w", aqua_hideout_storage_w)
aqua_hideout_storage_w:setHubIcon(aqua_hideout_storage_w_hub)
local aqua_hideout_storage_e = DoorSlot("aqua_hideout", "storage_e")
local aqua_hideout_storage_e_hub = DoorSlotHub("aqua_hideout", "storage_e", aqua_hideout_storage_e)
aqua_hideout_storage_e:setHubIcon(aqua_hideout_storage_e_hub)
local aqua_hideout_long_nw = DoorSlot("aqua_hideout", "long_nw")
local aqua_hideout_long_nw_hub = DoorSlotHub("aqua_hideout", "long_nw", aqua_hideout_long_nw)
aqua_hideout_long_nw:setHubIcon(aqua_hideout_long_nw_hub)
local aqua_hideout_long_sw = DoorSlot("aqua_hideout", "long_sw")
local aqua_hideout_long_sw_hub = DoorSlotHub("aqua_hideout", "long_sw", aqua_hideout_long_sw)
aqua_hideout_long_sw:setHubIcon(aqua_hideout_long_sw_hub)
local aqua_hideout_long_e = DoorSlot("aqua_hideout", "long_e")
local aqua_hideout_long_e_hub = DoorSlotHub("aqua_hideout", "long_e", aqua_hideout_long_e)
aqua_hideout_long_e:setHubIcon(aqua_hideout_long_e_hub)
local aqua_hideout_warps1_n = DoorSlot("aqua_hideout", "warps1_n")
local aqua_hideout_warps1_n_hub = DoorSlotHub("aqua_hideout", "warps1_n", aqua_hideout_warps1_n)
aqua_hideout_warps1_n:setHubIcon(aqua_hideout_warps1_n_hub)
local aqua_hideout_warps1_w = DoorSlot("aqua_hideout", "warps1_w")
local aqua_hideout_warps1_w_hub = DoorSlotHub("aqua_hideout", "warps1_w", aqua_hideout_warps1_w)
aqua_hideout_warps1_w:setHubIcon(aqua_hideout_warps1_w_hub)
local aqua_hideout_warps1_c = DoorSlot("aqua_hideout", "warps1_c")
local aqua_hideout_warps1_c_hub = DoorSlotHub("aqua_hideout", "warps1_c", aqua_hideout_warps1_c)
aqua_hideout_warps1_c:setHubIcon(aqua_hideout_warps1_c_hub)
local aqua_hideout_warps1_e = DoorSlot("aqua_hideout", "warps1_e")
local aqua_hideout_warps1_e_hub = DoorSlotHub("aqua_hideout", "warps1_e", aqua_hideout_warps1_e)
aqua_hideout_warps1_e:setHubIcon(aqua_hideout_warps1_e_hub)
local aqua_hideout_warps2_w = DoorSlot("aqua_hideout", "warps2_w")
local aqua_hideout_warps2_w_hub = DoorSlotHub("aqua_hideout", "warps2_w", aqua_hideout_warps2_w)
aqua_hideout_warps2_w:setHubIcon(aqua_hideout_warps2_w_hub)
local aqua_hideout_warps2_c = DoorSlot("aqua_hideout", "warps2_c")
local aqua_hideout_warps2_c_hub = DoorSlotHub("aqua_hideout", "warps2_c", aqua_hideout_warps2_c)
aqua_hideout_warps2_c:setHubIcon(aqua_hideout_warps2_c_hub)
local aqua_hideout_warps2_e = DoorSlot("aqua_hideout", "warps2_e")
local aqua_hideout_warps2_e_hub = DoorSlotHub("aqua_hideout", "warps2_e", aqua_hideout_warps2_e)
aqua_hideout_warps2_e:setHubIcon(aqua_hideout_warps2_e_hub)
local aqua_hideout_warps3_w = DoorSlot("aqua_hideout", "warps3_w")
local aqua_hideout_warps3_w_hub = DoorSlotHub("aqua_hideout", "warps3_w", aqua_hideout_warps3_w)
aqua_hideout_warps3_w:setHubIcon(aqua_hideout_warps3_w_hub)
local aqua_hideout_warps3_c = DoorSlot("aqua_hideout", "warps3_c")
local aqua_hideout_warps3_c_hub = DoorSlotHub("aqua_hideout", "warps3_c", aqua_hideout_warps3_c)
aqua_hideout_warps3_c:setHubIcon(aqua_hideout_warps3_c_hub)
local aqua_hideout_warps3_e = DoorSlot("aqua_hideout", "warps3_e")
local aqua_hideout_warps3_e_hub = DoorSlotHub("aqua_hideout", "warps3_e", aqua_hideout_warps3_e)
aqua_hideout_warps3_e:setHubIcon(aqua_hideout_warps3_e_hub)
local aqua_hideout_warps4_w = DoorSlot("aqua_hideout", "warps4_w")
local aqua_hideout_warps4_w_hub = DoorSlotHub("aqua_hideout", "warps4_w", aqua_hideout_warps4_w)
aqua_hideout_warps4_w:setHubIcon(aqua_hideout_warps4_w_hub)
local aqua_hideout_warps4_c = DoorSlot("aqua_hideout", "warps4_c")
local aqua_hideout_warps4_c_hub = DoorSlotHub("aqua_hideout", "warps4_c", aqua_hideout_warps4_c)
aqua_hideout_warps4_c:setHubIcon(aqua_hideout_warps4_c_hub)
local aqua_hideout_warps4_e = DoorSlot("aqua_hideout", "warps4_e")
local aqua_hideout_warps4_e_hub = DoorSlotHub("aqua_hideout", "warps4_e", aqua_hideout_warps4_e)
aqua_hideout_warps4_e:setHubIcon(aqua_hideout_warps4_e_hub)