local dept_0 = DoorSlot("dept","0")
local dept_0_hub = DoorSlotHub("dept","0",dept_0)
dept_0:setHubIcon(dept_0_hub)
local dept_1 = DoorSlot("dept","1")
local dept_1_hub = DoorSlotHub("dept","1",dept_1)
dept_1:setHubIcon(dept_1_hub)
local dept_2 = DoorSlot("dept","2")
local dept_2_hub = DoorSlotHub("dept","2",dept_2)
dept_2:setHubIcon(dept_2_hub)
local dept_3 = DoorSlot("dept","3")
local dept_3_hub = DoorSlotHub("dept","3",dept_3)
dept_3:setHubIcon(dept_3_hub)
local dept_4 = DoorSlot("dept","4")
local dept_4_hub = DoorSlotHub("dept","4",dept_4)
dept_4:setHubIcon(dept_4_hub)
local dept_5 = DoorSlot("dept","5")
local dept_5_hub = DoorSlotHub("dept","5",dept_5)
dept_5:setHubIcon(dept_5_hub)
local dept_6 = DoorSlot("dept","6")
local dept_6_hub = DoorSlotHub("dept","6",dept_6)
dept_6:setHubIcon(dept_6_hub)
local dept_7 = DoorSlot("dept","7")
local dept_7_hub = DoorSlotHub("dept","7",dept_7)
dept_7:setHubIcon(dept_7_hub)
local dept_8 = DoorSlot("dept","8")
local dept_8_hub = DoorSlotHub("dept","8",dept_8)
dept_8:setHubIcon(dept_8_hub)
local dept_9 = DoorSlot("dept","9")
local dept_9_hub = DoorSlotHub("dept","9",dept_9)
dept_9:setHubIcon(dept_9_hub)
