local dewford_center = DoorSlot("dewford", "center")
local dewford_center_hub = DoorSlotHub("dewford", "center", dewford_center)
dewford_center:setHubIcon(dewford_center_hub)
local dewford_house_se = DoorSlot("dewford", "house_se")
local dewford_house_se_hub = DoorSlotHub("dewford", "house_se", dewford_house_se)
dewford_house_se:setHubIcon(dewford_house_se_hub)
local dewford_house_c = DoorSlot("dewford", "house_c")
local dewford_house_c_hub = DoorSlotHub("dewford", "house_c", dewford_house_c)
dewford_house_c:setHubIcon(dewford_house_c_hub)
local dewford_house_nw = DoorSlot("dewford", "house_nw")
local dewford_house_nw_hub = DoorSlotHub("dewford", "house_nw", dewford_house_nw)
dewford_house_nw:setHubIcon(dewford_house_nw_hub)
local dewford_gym = DoorSlot("dewford", "gym")
local dewford_gym_hub = DoorSlotHub("dewford", "gym", dewford_gym)
dewford_gym:setHubIcon(dewford_gym_hub)