DoorSlot("ever_grande", "center", DoorSlotHub("ever_grande", "center"))
DoorSlot("ever_grande", "cave", DoorSlotHub("ever_grande", "cave"))
DoorSlot("ever_grande_center", "entrance", DoorSlotHub("ever_grande_center", "entrance"))
DoorSlot("ever_grande_center", "stairs", DoorSlotHub("ever_grande_center", "stairs"))
DoorSlot("ever_grande_center", "e4", DoorSlotHub("ever_grande_center", "e4"))