local ever_grande_center = DoorSlot("ever_grande", "center")
local ever_grande_center_hub = DoorSlotHub("ever_grande", "center", ever_grande_center)
ever_grande_center:setHubIcon(ever_grande_center_hub)
local ever_grande_cave = DoorSlot("ever_grande", "cave")
local ever_grande_cave_hub = DoorSlotHub("ever_grande", "cave", ever_grande_cave)
ever_grande_cave:setHubIcon(ever_grande_cave_hub)
local ever_grande_center_entrance = DoorSlot("ever_grande_center", "entrance")
local ever_grande_center_entrance_hub = DoorSlotHub("ever_grande_center", "entrance", ever_grande_center_entrance)
ever_grande_center_entrance:setHubIcon(ever_grande_center_entrance_hub)
local ever_grande_center_stairs = DoorSlot("ever_grande_center", "stairs")
local ever_grande_center_stairs_hub = DoorSlotHub("ever_grande_center", "stairs", ever_grande_center_stairs)
ever_grande_center_stairs:setHubIcon(ever_grande_center_stairs_hub)
local ever_grande_center_e4 = DoorSlot("ever_grande_center", "e4")
local ever_grande_center_e4_hub = DoorSlotHub("ever_grande_center", "e4", ever_grande_center_e4)
ever_grande_center_e4:setHubIcon(ever_grande_center_e4_hub)