local fallarbor_center = DoorSlot("fallarbor", "center")
local fallarbor_center_hub = DoorSlotHub("fallarbor", "center", fallarbor_center)
fallarbor_center:setHubIcon(fallarbor_center_hub)
local fallarbor_house_sw = DoorSlot("fallarbor", "house_sw")
local fallarbor_house_sw_hub = DoorSlotHub("fallarbor", "house_sw", fallarbor_house_sw)
fallarbor_house_sw:setHubIcon(fallarbor_house_sw_hub)
local fallarbor_house_nw = DoorSlot("fallarbor", "house_nw")
local fallarbor_house_nw_hub = DoorSlotHub("fallarbor", "house_nw", fallarbor_house_nw)
fallarbor_house_nw:setHubIcon(fallarbor_house_nw_hub)
local fallarbor_mart = DoorSlot("fallarbor", "mart")
local fallarbor_mart_hub = DoorSlotHub("fallarbor", "mart", fallarbor_mart)
fallarbor_mart:setHubIcon(fallarbor_mart_hub)
local fallarbor_contest = DoorSlot("fallarbor", "contest")
local fallarbor_contest_hub = DoorSlotHub("fallarbor", "contest", fallarbor_contest)
fallarbor_contest:setHubIcon(fallarbor_contest_hub)