local fortree_center = DoorSlot("fortree", "center")
local fortree_center_hub = DoorSlotHub("fortree", "center", fortree_center)
fortree_center:setHubIcon(fortree_center_hub)
local fortree_house_sw = DoorSlot("fortree", "house_sw")
local fortree_house_sw_hub = DoorSlotHub("fortree", "house_sw", fortree_house_sw)
fortree_house_sw:setHubIcon(fortree_house_sw_hub)
local fortree_house_se = DoorSlot("fortree", "house_se")
local fortree_house_se_hub = DoorSlotHub("fortree", "house_se", fortree_house_se)
fortree_house_se:setHubIcon(fortree_house_se_hub)
local fortree_house_n1 = DoorSlot("fortree", "house_n1")
local fortree_house_n1_hub = DoorSlotHub("fortree", "house_n1", fortree_house_n1)
fortree_house_n1:setHubIcon(fortree_house_n1_hub)
local fortree_house_n2 = DoorSlot("fortree", "house_n2")
local fortree_house_n2_hub = DoorSlotHub("fortree", "house_n2", fortree_house_n2)
fortree_house_n2:setHubIcon(fortree_house_n2_hub)
local fortree_house_n3 = DoorSlot("fortree", "house_n3")
local fortree_house_n3_hub = DoorSlotHub("fortree", "house_n3", fortree_house_n3)
fortree_house_n3:setHubIcon(fortree_house_n3_hub)
local fortree_house_n4 = DoorSlot("fortree", "house_n4")
local fortree_house_n4_hub = DoorSlotHub("fortree", "house_n4", fortree_house_n4)
fortree_house_n4:setHubIcon(fortree_house_n4_hub)
local fortree_mart = DoorSlot("fortree", "mart")
local fortree_mart_hub = DoorSlotHub("fortree", "mart", fortree_mart)
fortree_mart:setHubIcon(fortree_mart_hub)
local fortree_gym = DoorSlot("fortree", "gym")
local fortree_gym_hub = DoorSlotHub("fortree", "gym", fortree_gym)
fortree_gym:setHubIcon(fortree_gym_hub)