local granite_1f_hole_w = DoorSlot("granite", "1f_hole_w")
local granite_1f_hole_w_hub = DoorSlotHub("granite", "1f_hole_w", granite_1f_hole_w)
granite_1f_hole_w:setHubIcon(granite_1f_hole_w_hub)
local granite_1f_hole_e = DoorSlot("granite", "1f_hole_e")
local granite_1f_hole_e_hub = DoorSlotHub("granite", "1f_hole_e", granite_1f_hole_e)
granite_1f_hole_e:setHubIcon(granite_1f_hole_e_hub)
local granite_1f_ladder_w = DoorSlot("granite", "1f_ladder_w")
local granite_1f_ladder_w_hub = DoorSlotHub("granite", "1f_ladder_w", granite_1f_ladder_w)
granite_1f_ladder_w:setHubIcon(granite_1f_ladder_w_hub)
local granite_1f_ladder_e = DoorSlot("granite", "1f_ladder_e")
local granite_1f_ladder_e_hub = DoorSlotHub("granite", "1f_ladder_e", granite_1f_ladder_e)
granite_1f_ladder_e:setHubIcon(granite_1f_ladder_e_hub)
local granite_b1f_ladder_nw = DoorSlot("granite", "b1f_ladder_nw")
local granite_b1f_ladder_nw_hub = DoorSlotHub("granite", "b1f_ladder_nw", granite_b1f_ladder_nw)
granite_b1f_ladder_nw:setHubIcon(granite_b1f_ladder_nw_hub)
local granite_b1f_ladder_n = DoorSlot("granite", "b1f_ladder_n")
local granite_b1f_ladder_n_hub = DoorSlotHub("granite", "b1f_ladder_n", granite_b1f_ladder_n)
granite_b1f_ladder_n:setHubIcon(granite_b1f_ladder_n_hub)
local granite_b1f_ladder_ne = DoorSlot("granite", "b1f_ladder_ne")
local granite_b1f_ladder_ne_hub = DoorSlotHub("granite", "b1f_ladder_ne", granite_b1f_ladder_ne)
granite_b1f_ladder_ne:setHubIcon(granite_b1f_ladder_ne_hub)
local granite_b1f_ladder_sw = DoorSlot("granite", "b1f_ladder_sw")
local granite_b1f_ladder_sw_hub = DoorSlotHub("granite", "b1f_ladder_sw", granite_b1f_ladder_sw)
granite_b1f_ladder_sw:setHubIcon(granite_b1f_ladder_sw_hub)
local granite_b1f_ladder_se = DoorSlot("granite", "b1f_ladder_se")
local granite_b1f_ladder_se_hub = DoorSlotHub("granite", "b1f_ladder_se", granite_b1f_ladder_se)
granite_b1f_ladder_se:setHubIcon(granite_b1f_ladder_se_hub)
local granite_b2f_ladder_w = DoorSlot("granite", "b2f_ladder_w")
local granite_b2f_ladder_w_hub = DoorSlotHub("granite", "b2f_ladder_w", granite_b2f_ladder_w)
granite_b2f_ladder_w:setHubIcon(granite_b2f_ladder_w_hub)
local granite_b2f_ladder_e = DoorSlot("granite", "b2f_ladder_e")
local granite_b2f_ladder_e_hub = DoorSlotHub("granite", "b2f_ladder_e", granite_b2f_ladder_e)
granite_b2f_ladder_e:setHubIcon(granite_b2f_ladder_e_hub)