local jagged_pass_n = DoorSlot("jagged_pass", "n")
local jagged_pass_n_hub = DoorSlotHub("jagged_pass", "n", jagged_pass_n)
jagged_pass_n:setHubIcon(jagged_pass_n_hub)
local jagged_pass_magma = DoorSlot("jagged_pass", "magma")
local jagged_pass_magma_hub = DoorSlotHub("jagged_pass", "magma", jagged_pass_magma)
jagged_pass_magma:setHubIcon(jagged_pass_magma_hub)
local jagged_pass_s = DoorSlot("jagged_pass", "s")
local jagged_pass_s_hub = DoorSlotHub("jagged_pass", "s", jagged_pass_s)
jagged_pass_s:setHubIcon(jagged_pass_s_hub)