local lavaridge_center = DoorSlot("lavaridge", "center")
local lavaridge_center_hub = DoorSlotHub("lavaridge", "center", lavaridge_center)
lavaridge_center:setHubIcon(lavaridge_center_hub)
local lavaridge_house_se = DoorSlot("lavaridge", "house_se")
local lavaridge_house_se_hub = DoorSlotHub("lavaridge", "house_se", lavaridge_house_se)
lavaridge_house_se:setHubIcon(lavaridge_house_se_hub)
local lavaridge_house_s = DoorSlot("lavaridge", "house_s")
local lavaridge_house_s_hub = DoorSlotHub("lavaridge", "house_s", lavaridge_house_s)
lavaridge_house_s:setHubIcon(lavaridge_house_s_hub)
local lavaridge_mart = DoorSlot("lavaridge", "mart")
local lavaridge_mart_hub = DoorSlotHub("lavaridge", "mart", lavaridge_mart)
lavaridge_mart:setHubIcon(lavaridge_mart_hub)
local lavaridge_gym = DoorSlot("lavaridge", "gym")
local lavaridge_gym_hub = DoorSlotHub("lavaridge", "gym", lavaridge_gym)
lavaridge_gym:setHubIcon(lavaridge_gym_hub)
local lavaridge_center_entrance = DoorSlot("lavaridge_center", "entrance")
local lavaridge_center_entrance_hub = DoorSlotHub("lavaridge_center", "entrance", lavaridge_center_entrance)
lavaridge_center_entrance:setHubIcon(lavaridge_center_entrance_hub)
local lavaridge_center_stairs = DoorSlot("lavaridge_center", "stairs")
local lavaridge_center_stairs_hub = DoorSlotHub("lavaridge_center", "stairs", lavaridge_center_stairs)
lavaridge_center_stairs:setHubIcon(lavaridge_center_stairs_hub)
local lavaridge_center_hot_spring = DoorSlot("lavaridge_center", "hot_spring")
local lavaridge_center_hot_spring_hub = DoorSlotHub("lavaridge_center", "hot_spring", lavaridge_center_hot_spring)
lavaridge_center_hot_spring:setHubIcon(lavaridge_center_hot_spring_hub)