DoorSlot("lavaridge", "center", DoorSlotHub("lavaridge", "center"))
DoorSlot("lavaridge", "house_se", DoorSlotHub("lavaridge", "house_se"))
DoorSlot("lavaridge", "house_s", DoorSlotHub("lavaridge", "house_s"))
DoorSlot("lavaridge", "mart", DoorSlotHub("lavaridge", "mart"))
DoorSlot("lavaridge", "gym", DoorSlotHub("lavaridge", "gym"))
DoorSlot("lavaridge_center", "entrance", DoorSlotHub("lavaridge_center", "entrance"))
DoorSlot("lavaridge_center", "stairs", DoorSlotHub("lavaridge_center", "stairs"))
DoorSlot("lavaridge_center", "hot_spring", DoorSlotHub("lavaridge_center", "hot_spring"))