local lilycove_center = DoorSlot("lilycove", "center")
local lilycove_center_hub = DoorSlotHub("lilycove", "center", lilycove_center)
lilycove_center:setHubIcon(lilycove_center_hub)
local lilycove_house_sw = DoorSlot("lilycove", "house_sw")
local lilycove_house_sw_hub = DoorSlotHub("lilycove", "house_sw", lilycove_house_sw)
lilycove_house_sw:setHubIcon(lilycove_house_sw_hub)
local lilycove_house_w = DoorSlot("lilycove", "house_w")
local lilycove_house_w_hub = DoorSlotHub("lilycove", "house_w", lilycove_house_w)
lilycove_house_w:setHubIcon(lilycove_house_w_hub)
local lilycove_house_c = DoorSlot("lilycove", "house_c")
local lilycove_house_c_hub = DoorSlotHub("lilycove", "house_c", lilycove_house_c)
lilycove_house_c:setHubIcon(lilycove_house_c_hub)
local lilycove_house_n = DoorSlot("lilycove", "house_n")
local lilycove_house_n_hub = DoorSlotHub("lilycove", "house_n", lilycove_house_n)
lilycove_house_n:setHubIcon(lilycove_house_n_hub)
local lilycove_house_ne = DoorSlot("lilycove", "house_ne")
local lilycove_house_ne_hub = DoorSlotHub("lilycove", "house_ne", lilycove_house_ne)
lilycove_house_ne:setHubIcon(lilycove_house_ne_hub)
local lilycove_house_e = DoorSlot("lilycove", "house_e")
local lilycove_house_e_hub = DoorSlotHub("lilycove", "house_e", lilycove_house_e)
lilycove_house_e:setHubIcon(lilycove_house_e_hub)
local lilycove_dept = DoorSlot("lilycove", "dept")
local lilycove_dept_hub = DoorSlotHub("lilycove", "dept", lilycove_dept)
lilycove_dept:setHubIcon(lilycove_dept_hub)
local lilycove_contest = DoorSlot("lilycove", "contest")
local lilycove_contest_hub = DoorSlotHub("lilycove", "contest", lilycove_contest)
lilycove_contest:setHubIcon(lilycove_contest_hub)
local lilycove_harbor = DoorSlot("lilycove", "harbor")
local lilycove_harbor_hub = DoorSlotHub("lilycove", "harbor", lilycove_harbor)
lilycove_harbor:setHubIcon(lilycove_harbor_hub)
local lilycove_motel = DoorSlot("lilycove", "motel")
local lilycove_motel_hub = DoorSlotHub("lilycove", "motel", lilycove_motel)
lilycove_motel:setHubIcon(lilycove_motel_hub)
local lilycove_aqua = DoorSlot("lilycove", "aqua")
local lilycove_aqua_hub = DoorSlotHub("lilycove", "aqua", lilycove_aqua)
lilycove_aqua:setHubIcon(lilycove_aqua_hub)
local lilycove_contest_entrance = DoorSlot("lilycove_contest", "entrance")
local lilycove_contest_entrance_hub = DoorSlotHub("lilycove_contest", "entrance", lilycove_contest_entrance)
lilycove_contest_entrance:setHubIcon(lilycove_contest_entrance_hub)
local lilycove_contest_nw = DoorSlot("lilycove_contest", "nw")
local lilycove_contest_nw_hub = DoorSlotHub("lilycove_contest", "nw", lilycove_contest_nw)
lilycove_contest_nw:setHubIcon(lilycove_contest_nw_hub)
local lilycove_contest_ne = DoorSlot("lilycove_contest", "ne")
local lilycove_contest_ne_hub = DoorSlotHub("lilycove_contest", "ne", lilycove_contest_ne)
lilycove_contest_ne:setHubIcon(lilycove_contest_ne_hub)
local lilycove_dept_1f_entrance = DoorSlot("lilycove_dept", "1f_entrance")
local lilycove_dept_1f_entrance_hub = DoorSlotHub("lilycove_dept", "1f_entrance", lilycove_dept_1f_entrance)
lilycove_dept_1f_entrance:setHubIcon(lilycove_dept_1f_entrance_hub)
local lilycove_dept_1f_stairs = DoorSlot("lilycove_dept", "1f_stairs")
local lilycove_dept_1f_stairs_hub = DoorSlotHub("lilycove_dept", "1f_stairs", lilycove_dept_1f_stairs)
lilycove_dept_1f_stairs:setHubIcon(lilycove_dept_1f_stairs_hub)
local lilycove_dept_2f_l = DoorSlot("lilycove_dept", "2f_l")
local lilycove_dept_2f_l_hub = DoorSlotHub("lilycove_dept", "2f_l", lilycove_dept_2f_l)
lilycove_dept_2f_l:setHubIcon(lilycove_dept_2f_l_hub)
local lilycove_dept_2f_r = DoorSlot("lilycove_dept", "2f_r")
local lilycove_dept_2f_r_hub = DoorSlotHub("lilycove_dept", "2f_r", lilycove_dept_2f_r)
lilycove_dept_2f_r:setHubIcon(lilycove_dept_2f_r_hub)
local lilycove_dept_3f_l = DoorSlot("lilycove_dept", "3f_l")
local lilycove_dept_3f_l_hub = DoorSlotHub("lilycove_dept", "3f_l", lilycove_dept_3f_l)
lilycove_dept_3f_l:setHubIcon(lilycove_dept_3f_l_hub)
local lilycove_dept_3f_r = DoorSlot("lilycove_dept", "3f_r")
local lilycove_dept_3f_r_hub = DoorSlotHub("lilycove_dept", "3f_r", lilycove_dept_3f_r)
lilycove_dept_3f_r:setHubIcon(lilycove_dept_3f_r_hub)
local lilycove_dept_4f_l = DoorSlot("lilycove_dept", "4f_l")
local lilycove_dept_4f_l_hub = DoorSlotHub("lilycove_dept", "4f_l", lilycove_dept_4f_l)
lilycove_dept_4f_l:setHubIcon(lilycove_dept_4f_l_hub)
local lilycove_dept_4f_r = DoorSlot("lilycove_dept", "4f_r")
local lilycove_dept_4f_r_hub = DoorSlotHub("lilycove_dept", "4f_r", lilycove_dept_4f_r)
lilycove_dept_4f_r:setHubIcon(lilycove_dept_4f_r_hub)
local lilycove_dept_5f_l = DoorSlot("lilycove_dept", "5f_l")
local lilycove_dept_5f_l_hub = DoorSlotHub("lilycove_dept", "5f_l", lilycove_dept_5f_l)
lilycove_dept_5f_l:setHubIcon(lilycove_dept_5f_l_hub)
local lilycove_dept_5f_r = DoorSlot("lilycove_dept", "5f_r")
local lilycove_dept_5f_r_hub = DoorSlotHub("lilycove_dept", "5f_r", lilycove_dept_5f_r)
lilycove_dept_5f_r:setHubIcon(lilycove_dept_5f_r_hub)