local magma_hideout_1f_sw = DoorSlot("magma_hideout", "1f_sw")
local magma_hideout_1f_sw_hub = DoorSlotHub("magma_hideout", "1f_sw", magma_hideout_1f_sw)
magma_hideout_1f_sw:setHubIcon(magma_hideout_1f_sw_hub)
local magma_hideout_1f_se = DoorSlot("magma_hideout", "1f_se")
local magma_hideout_1f_se_hub = DoorSlotHub("magma_hideout", "1f_se", magma_hideout_1f_se)
magma_hideout_1f_se:setHubIcon(magma_hideout_1f_se_hub)
local magma_hideout_1f_c = DoorSlot("magma_hideout", "1f_c")
local magma_hideout_1f_c_hub = DoorSlotHub("magma_hideout", "1f_c", magma_hideout_1f_c)
magma_hideout_1f_c:setHubIcon(magma_hideout_1f_c_hub)
local magma_hideout_2f_n = DoorSlot("magma_hideout", "2f_n")
local magma_hideout_2f_n_hub = DoorSlotHub("magma_hideout", "2f_n", magma_hideout_2f_n)
magma_hideout_2f_n:setHubIcon(magma_hideout_2f_n_hub)
local magma_hideout_2f_c = DoorSlot("magma_hideout", "2f_c")
local magma_hideout_2f_c_hub = DoorSlotHub("magma_hideout", "2f_c", magma_hideout_2f_c)
magma_hideout_2f_c:setHubIcon(magma_hideout_2f_c_hub)
local magma_hideout_2f_s = DoorSlot("magma_hideout", "2f_s")
local magma_hideout_2f_s_hub = DoorSlotHub("magma_hideout", "2f_s", magma_hideout_2f_s)
magma_hideout_2f_s:setHubIcon(magma_hideout_2f_s_hub)
local magma_hideout_3f_n = DoorSlot("magma_hideout", "3f_n")
local magma_hideout_3f_n_hub = DoorSlotHub("magma_hideout", "3f_n", magma_hideout_3f_n)
magma_hideout_3f_n:setHubIcon(magma_hideout_3f_n_hub)
local magma_hideout_3f_c = DoorSlot("magma_hideout", "3f_c")
local magma_hideout_3f_c_hub = DoorSlotHub("magma_hideout", "3f_c", magma_hideout_3f_c)
magma_hideout_3f_c:setHubIcon(magma_hideout_3f_c_hub)
local magma_hideout_3f_s = DoorSlot("magma_hideout", "3f_s")
local magma_hideout_3f_s_hub = DoorSlotHub("magma_hideout", "3f_s", magma_hideout_3f_s)
magma_hideout_3f_s:setHubIcon(magma_hideout_3f_s_hub)