local mauville_center = DoorSlot("mauville", "center")
local mauville_center_hub = DoorSlotHub("mauville", "center", mauville_center)
mauville_center:setHubIcon(mauville_center_hub)
local mauville_house_se = DoorSlot("mauville", "house_se")
local mauville_house_se_hub = DoorSlotHub("mauville", "house_se", mauville_house_se)
mauville_house_se:setHubIcon(mauville_house_se_hub)
local mauville_house_sw = DoorSlot("mauville", "house_sw")
local mauville_house_sw_hub = DoorSlotHub("mauville", "house_sw", mauville_house_sw)
mauville_house_sw:setHubIcon(mauville_house_sw_hub)
local mauville_mart = DoorSlot("mauville", "mart")
local mauville_mart_hub = DoorSlotHub("mauville", "mart", mauville_mart)
mauville_mart:setHubIcon(mauville_mart_hub)
local mauville_gym = DoorSlot("mauville", "gym")
local mauville_gym_hub = DoorSlotHub("mauville", "gym", mauville_gym)
mauville_gym:setHubIcon(mauville_gym_hub)
local mauville_casino = DoorSlot("mauville", "casino")
local mauville_casino_hub = DoorSlotHub("mauville", "casino", mauville_casino)
mauville_casino:setHubIcon(mauville_casino_hub)
local mauville_bike = DoorSlot("mauville", "bike")
local mauville_bike_hub = DoorSlotHub("mauville", "bike", mauville_bike)
mauville_bike:setHubIcon(mauville_bike_hub)