local meteor_falls_front_n = DoorSlot("meteor_falls", "front_n")
local meteor_falls_front_n_hub = DoorSlotHub("meteor_falls", "front_n", meteor_falls_front_n)
meteor_falls_front_n:setHubIcon(meteor_falls_front_n_hub)
local meteor_falls_front_e = DoorSlot("meteor_falls", "front_e")
local meteor_falls_front_e_hub = DoorSlotHub("meteor_falls", "front_e", meteor_falls_front_e)
meteor_falls_front_e:setHubIcon(meteor_falls_front_e_hub)
local meteor_falls_front_s = DoorSlot("meteor_falls", "front_s")
local meteor_falls_front_s_hub = DoorSlotHub("meteor_falls", "front_s", meteor_falls_front_s)
meteor_falls_front_s:setHubIcon(meteor_falls_front_s_hub)
local meteor_falls_back_nw = DoorSlot("meteor_falls", "back_nw")
local meteor_falls_back_nw_hub = DoorSlotHub("meteor_falls", "back_nw", meteor_falls_back_nw)
meteor_falls_back_nw:setHubIcon(meteor_falls_back_nw_hub)
local meteor_falls_back_w = DoorSlot("meteor_falls", "back_w")
local meteor_falls_back_w_hub = DoorSlotHub("meteor_falls", "back_w", meteor_falls_back_w)
meteor_falls_back_w:setHubIcon(meteor_falls_back_w_hub)
local meteor_falls_back_sw = DoorSlot("meteor_falls", "back_sw")
local meteor_falls_back_sw_hub = DoorSlotHub("meteor_falls", "back_sw", meteor_falls_back_sw)
meteor_falls_back_sw:setHubIcon(meteor_falls_back_sw_hub)
local meteor_falls_back_e = DoorSlot("meteor_falls", "back_e")
local meteor_falls_back_e_hub = DoorSlotHub("meteor_falls", "back_e", meteor_falls_back_e)
meteor_falls_back_e:setHubIcon(meteor_falls_back_e_hub)
local meteor_falls_b1f_e_n = DoorSlot("meteor_falls", "b1f_e_n")
local meteor_falls_b1f_e_n_hub = DoorSlotHub("meteor_falls", "b1f_e_n", meteor_falls_b1f_e_n)
meteor_falls_b1f_e_n:setHubIcon(meteor_falls_b1f_e_n_hub)
local meteor_falls_b1f_e_w = DoorSlot("meteor_falls", "b1f_e_w")
local meteor_falls_b1f_e_w_hub = DoorSlotHub("meteor_falls", "b1f_e_w", meteor_falls_b1f_e_w)
meteor_falls_b1f_e_w:setHubIcon(meteor_falls_b1f_e_w_hub)
local meteor_falls_b1f_e_s = DoorSlot("meteor_falls", "b1f_e_s")
local meteor_falls_b1f_e_s_hub = DoorSlotHub("meteor_falls", "b1f_e_s", meteor_falls_b1f_e_s)
meteor_falls_b1f_e_s:setHubIcon(meteor_falls_b1f_e_s_hub)
local meteor_falls_b1f_w_n = DoorSlot("meteor_falls", "b1f_w_n")
local meteor_falls_b1f_w_n_hub = DoorSlotHub("meteor_falls", "b1f_w_n", meteor_falls_b1f_w_n)
meteor_falls_b1f_w_n:setHubIcon(meteor_falls_b1f_w_n_hub)
local meteor_falls_b1f_w_e = DoorSlot("meteor_falls", "b1f_w_e")
local meteor_falls_b1f_w_e_hub = DoorSlotHub("meteor_falls", "b1f_w_e", meteor_falls_b1f_w_e)
meteor_falls_b1f_w_e:setHubIcon(meteor_falls_b1f_w_e_hub)
local meteor_falls_b1f_w_sw = DoorSlot("meteor_falls", "b1f_w_sw")
local meteor_falls_b1f_w_sw_hub = DoorSlotHub("meteor_falls", "b1f_w_sw", meteor_falls_b1f_w_sw)
meteor_falls_b1f_w_sw:setHubIcon(meteor_falls_b1f_w_sw_hub)