local mirage_tower_1f_s = DoorSlot("mirage_tower", "1f_s")
local mirage_tower_1f_s_hub = DoorSlotHub("mirage_tower", "1f_s", mirage_tower_1f_s)
mirage_tower_1f_s:setHubIcon(mirage_tower_1f_s_hub)
local mirage_tower_1f_n = DoorSlot("mirage_tower", "1f_n")
local mirage_tower_1f_n_hub = DoorSlotHub("mirage_tower", "1f_n", mirage_tower_1f_n)
mirage_tower_1f_n:setHubIcon(mirage_tower_1f_n_hub)
local mirage_tower_2f_s = DoorSlot("mirage_tower", "2f_s")
local mirage_tower_2f_s_hub = DoorSlotHub("mirage_tower", "2f_s", mirage_tower_2f_s)
mirage_tower_2f_s:setHubIcon(mirage_tower_2f_s_hub)
local mirage_tower_2f_n = DoorSlot("mirage_tower", "2f_n")
local mirage_tower_2f_n_hub = DoorSlotHub("mirage_tower", "2f_n", mirage_tower_2f_n)
mirage_tower_2f_n:setHubIcon(mirage_tower_2f_n_hub)
local mirage_tower_3f_s = DoorSlot("mirage_tower", "3f_s")
local mirage_tower_3f_s_hub = DoorSlotHub("mirage_tower", "3f_s", mirage_tower_3f_s)
mirage_tower_3f_s:setHubIcon(mirage_tower_3f_s_hub)
local mirage_tower_3f_n = DoorSlot("mirage_tower", "3f_n")
local mirage_tower_3f_n_hub = DoorSlotHub("mirage_tower", "3f_n", mirage_tower_3f_n)
mirage_tower_3f_n:setHubIcon(mirage_tower_3f_n_hub)