local mossdeep_center = DoorSlot("mossdeep", "center")
local mossdeep_center_hub = DoorSlotHub("mossdeep", "center", mossdeep_center)
mossdeep_center:setHubIcon(mossdeep_center_hub)
local mossdeep_house_nw = DoorSlot("mossdeep", "house_nw")
local mossdeep_house_nw_hub = DoorSlotHub("mossdeep", "house_nw", mossdeep_house_nw)
mossdeep_house_nw:setHubIcon(mossdeep_house_nw_hub)
local mossdeep_house_n = DoorSlot("mossdeep", "house_n")
local mossdeep_house_n_hub = DoorSlotHub("mossdeep", "house_n", mossdeep_house_n)
mossdeep_house_n:setHubIcon(mossdeep_house_n_hub)
local mossdeep_house_ne = DoorSlot("mossdeep", "house_ne")
local mossdeep_house_ne_hub = DoorSlotHub("mossdeep", "house_ne", mossdeep_house_ne)
mossdeep_house_ne:setHubIcon(mossdeep_house_ne_hub)
local mossdeep_house_w = DoorSlot("mossdeep", "house_w")
local mossdeep_house_w_hub = DoorSlotHub("mossdeep", "house_w", mossdeep_house_w)
mossdeep_house_w:setHubIcon(mossdeep_house_w_hub)
local mossdeep_house_s = DoorSlot("mossdeep", "house_s")
local mossdeep_house_s_hub = DoorSlotHub("mossdeep", "house_s", mossdeep_house_s)
mossdeep_house_s:setHubIcon(mossdeep_house_s_hub)
local mossdeep_house_se = DoorSlot("mossdeep", "house_se")
local mossdeep_house_se_hub = DoorSlotHub("mossdeep", "house_se", mossdeep_house_se)
mossdeep_house_se:setHubIcon(mossdeep_house_se_hub)
local mossdeep_mart = DoorSlot("mossdeep", "mart")
local mossdeep_mart_hub = DoorSlotHub("mossdeep", "mart", mossdeep_mart)
mossdeep_mart:setHubIcon(mossdeep_mart_hub)
local mossdeep_gym = DoorSlot("mossdeep", "gym")
local mossdeep_gym_hub = DoorSlotHub("mossdeep", "gym", mossdeep_gym)
mossdeep_gym:setHubIcon(mossdeep_gym_hub)
local mossdeep_space = DoorSlot("mossdeep", "space")
local mossdeep_space_hub = DoorSlotHub("mossdeep", "space", mossdeep_space)
mossdeep_space:setHubIcon(mossdeep_space_hub)