local mt_pyre_1f_entrance_s = DoorSlot("mt_pyre", "1f_entrance_s")
local mt_pyre_1f_entrance_s_hub = DoorSlotHub("mt_pyre", "1f_entrance_s", mt_pyre_1f_entrance_s)
mt_pyre_1f_entrance_s:setHubIcon(mt_pyre_1f_entrance_s_hub)
local mt_pyre_1f_entrance_w = DoorSlot("mt_pyre", "1f_entrance_w")
local mt_pyre_1f_entrance_w_hub = DoorSlotHub("mt_pyre", "1f_entrance_w", mt_pyre_1f_entrance_w)
mt_pyre_1f_entrance_w:setHubIcon(mt_pyre_1f_entrance_w_hub)
local mt_pyre_1f_stairs = DoorSlot("mt_pyre", "1f_stairs")
local mt_pyre_1f_stairs_hub = DoorSlotHub("mt_pyre", "1f_stairs", mt_pyre_1f_stairs)
mt_pyre_1f_stairs:setHubIcon(mt_pyre_1f_stairs_hub)
local mt_pyre_1f_landing = DoorSlot("mt_pyre", "1f_landing")
local mt_pyre_1f_landing_hub = DoorSlotHub("mt_pyre", "1f_landing", mt_pyre_1f_landing)
mt_pyre_1f_landing:setHubIcon(mt_pyre_1f_landing_hub)
local mt_pyre_2f_stairs_nw = DoorSlot("mt_pyre", "2f_stairs_nw")
local mt_pyre_2f_stairs_nw_hub = DoorSlotHub("mt_pyre", "2f_stairs_nw", mt_pyre_2f_stairs_nw)
mt_pyre_2f_stairs_nw:setHubIcon(mt_pyre_2f_stairs_nw_hub)
local mt_pyre_2f_stairs_ne = DoorSlot("mt_pyre", "2f_stairs_ne")
local mt_pyre_2f_stairs_ne_hub = DoorSlotHub("mt_pyre", "2f_stairs_ne", mt_pyre_2f_stairs_ne)
mt_pyre_2f_stairs_ne:setHubIcon(mt_pyre_2f_stairs_ne_hub)
local mt_pyre_2f_hole = DoorSlot("mt_pyre", "2f_hole")
local mt_pyre_2f_hole_hub = DoorSlotHub("mt_pyre", "2f_hole", mt_pyre_2f_hole)
mt_pyre_2f_hole:setHubIcon(mt_pyre_2f_hole_hub)
local mt_pyre_2f_landing_sw = DoorSlot("mt_pyre", "2f_landing_sw")
local mt_pyre_2f_landing_sw_hub = DoorSlotHub("mt_pyre", "2f_landing_sw", mt_pyre_2f_landing_sw)
mt_pyre_2f_landing_sw:setHubIcon(mt_pyre_2f_landing_sw_hub)
local mt_pyre_2f_landing_se = DoorSlot("mt_pyre", "2f_landing_se")
local mt_pyre_2f_landing_se_hub = DoorSlotHub("mt_pyre", "2f_landing_se", mt_pyre_2f_landing_se)
mt_pyre_2f_landing_se:setHubIcon(mt_pyre_2f_landing_se_hub)
local mt_pyre_3f_stairs_nw = DoorSlot("mt_pyre", "3f_stairs_nw")
local mt_pyre_3f_stairs_nw_hub = DoorSlotHub("mt_pyre", "3f_stairs_nw", mt_pyre_3f_stairs_nw)
mt_pyre_3f_stairs_nw:setHubIcon(mt_pyre_3f_stairs_nw_hub)
local mt_pyre_3f_stairs_ne = DoorSlot("mt_pyre", "3f_stairs_ne")
local mt_pyre_3f_stairs_ne_hub = DoorSlotHub("mt_pyre", "3f_stairs_ne", mt_pyre_3f_stairs_ne)
mt_pyre_3f_stairs_ne:setHubIcon(mt_pyre_3f_stairs_ne_hub)
local mt_pyre_3f_hole = DoorSlot("mt_pyre", "3f_hole")
local mt_pyre_3f_hole_hub = DoorSlotHub("mt_pyre", "3f_hole", mt_pyre_3f_hole)
mt_pyre_3f_hole:setHubIcon(mt_pyre_3f_hole_hub)
local mt_pyre_3f_landing = DoorSlot("mt_pyre", "3f_landing")
local mt_pyre_3f_landing_hub = DoorSlotHub("mt_pyre", "3f_landing", mt_pyre_3f_landing)
mt_pyre_3f_landing:setHubIcon(mt_pyre_3f_landing_hub)
local mt_pyre_4f_stairs_nw = DoorSlot("mt_pyre", "4f_stairs_nw")
local mt_pyre_4f_stairs_nw_hub = DoorSlotHub("mt_pyre", "4f_stairs_nw", mt_pyre_4f_stairs_nw)
mt_pyre_4f_stairs_nw:setHubIcon(mt_pyre_4f_stairs_nw_hub)
local mt_pyre_4f_stairs_ne = DoorSlot("mt_pyre", "4f_stairs_ne")
local mt_pyre_4f_stairs_ne_hub = DoorSlotHub("mt_pyre", "4f_stairs_ne", mt_pyre_4f_stairs_ne)
mt_pyre_4f_stairs_ne:setHubIcon(mt_pyre_4f_stairs_ne_hub)
local mt_pyre_4f_hole = DoorSlot("mt_pyre", "4f_hole")
local mt_pyre_4f_hole_hub = DoorSlotHub("mt_pyre", "4f_hole", mt_pyre_4f_hole)
mt_pyre_4f_hole:setHubIcon(mt_pyre_4f_hole_hub)
local mt_pyre_4f_landing = DoorSlot("mt_pyre", "4f_landing")
local mt_pyre_4f_landing_hub = DoorSlotHub("mt_pyre", "4f_landing", mt_pyre_4f_landing)
mt_pyre_4f_landing:setHubIcon(mt_pyre_4f_landing_hub)
local mt_pyre_5f_landing = DoorSlot("mt_pyre", "5f_landing")
local mt_pyre_5f_landing_hub = DoorSlotHub("mt_pyre", "5f_landing", mt_pyre_5f_landing)
mt_pyre_5f_landing:setHubIcon(mt_pyre_5f_landing_hub)
local mt_pyre_5f_hole_se = DoorSlot("mt_pyre", "5f_hole_se")
local mt_pyre_5f_hole_se_hub = DoorSlotHub("mt_pyre", "5f_hole_se", mt_pyre_5f_hole_se)
mt_pyre_5f_hole_se:setHubIcon(mt_pyre_5f_hole_se_hub)
local mt_pyre_5f_hole_ne = DoorSlot("mt_pyre", "5f_hole_ne")
local mt_pyre_5f_hole_ne_hub = DoorSlotHub("mt_pyre", "5f_hole_ne", mt_pyre_5f_hole_ne)
mt_pyre_5f_hole_ne:setHubIcon(mt_pyre_5f_hole_ne_hub)