local navel_rock_ladder_nw = DoorSlot("navel_rock", "ladder_nw")
local navel_rock_ladder_nw_hub = DoorSlotHub("navel_rock", "ladder_nw", navel_rock_ladder_nw)
navel_rock_ladder_nw:setHubIcon(navel_rock_ladder_nw_hub)
local navel_rock_ladder_ne = DoorSlot("navel_rock", "ladder_ne")
local navel_rock_ladder_ne_hub = DoorSlotHub("navel_rock", "ladder_ne", navel_rock_ladder_ne)
navel_rock_ladder_ne:setHubIcon(navel_rock_ladder_ne_hub)
local navel_rock_ladder_s = DoorSlot("navel_rock", "ladder_s")
local navel_rock_ladder_s_hub = DoorSlotHub("navel_rock", "ladder_s", navel_rock_ladder_s)
navel_rock_ladder_s:setHubIcon(navel_rock_ladder_s_hub)