local oldale_center = DoorSlot("oldale", "center")
local oldale_center_hub = DoorSlotHub("oldale", "center", oldale_center)
oldale_center:setHubIcon(oldale_center_hub)
local oldale_house_se = DoorSlot("oldale", "house_se")
local oldale_house_se_hub = DoorSlotHub("oldale", "house_se", oldale_house_se)
oldale_house_se:setHubIcon(oldale_house_se_hub)
local oldale_house_nw = DoorSlot("oldale", "house_nw")
local oldale_house_nw_hub = DoorSlotHub("oldale", "house_nw", oldale_house_nw)
oldale_house_nw:setHubIcon(oldale_house_nw_hub)
local oldale_mart = DoorSlot("oldale", "mart")
local oldale_mart_hub = DoorSlotHub("oldale", "mart", oldale_mart)
oldale_mart:setHubIcon(oldale_mart_hub)