DoorSlot("pacifidlog", "center", DoorSlotHub("pacifidlog", "center"))
DoorSlot("pacifidlog", "house_sw", DoorSlotHub("pacifidlog", "house_sw"))
DoorSlot("pacifidlog", "house_s", DoorSlotHub("pacifidlog", "house_s"))
DoorSlot("pacifidlog", "house_se", DoorSlotHub("pacifidlog", "house_se"))
DoorSlot("pacifidlog", "house_nw", DoorSlotHub("pacifidlog", "house_nw"))
DoorSlot("pacifidlog", "house_ne", DoorSlotHub("pacifidlog", "house_ne"))