local pacifidlog_center = DoorSlot("pacifidlog", "center")
local pacifidlog_center_hub = DoorSlotHub("pacifidlog", "center", pacifidlog_center)
pacifidlog_center:setHubIcon(pacifidlog_center_hub)
local pacifidlog_house_sw = DoorSlot("pacifidlog", "house_sw")
local pacifidlog_house_sw_hub = DoorSlotHub("pacifidlog", "house_sw", pacifidlog_house_sw)
pacifidlog_house_sw:setHubIcon(pacifidlog_house_sw_hub)
local pacifidlog_house_s = DoorSlot("pacifidlog", "house_s")
local pacifidlog_house_s_hub = DoorSlotHub("pacifidlog", "house_s", pacifidlog_house_s)
pacifidlog_house_s:setHubIcon(pacifidlog_house_s_hub)
local pacifidlog_house_se = DoorSlot("pacifidlog", "house_se")
local pacifidlog_house_se_hub = DoorSlotHub("pacifidlog", "house_se", pacifidlog_house_se)
pacifidlog_house_se:setHubIcon(pacifidlog_house_se_hub)
local pacifidlog_house_nw = DoorSlot("pacifidlog", "house_nw")
local pacifidlog_house_nw_hub = DoorSlotHub("pacifidlog", "house_nw", pacifidlog_house_nw)
pacifidlog_house_nw:setHubIcon(pacifidlog_house_nw_hub)
local pacifidlog_house_ne = DoorSlot("pacifidlog", "house_ne")
local pacifidlog_house_ne_hub = DoorSlotHub("pacifidlog", "house_ne", pacifidlog_house_ne)
pacifidlog_house_ne:setHubIcon(pacifidlog_house_ne_hub)