local petalburg_woods_entrance_n = DoorSlot("petalburg_woods", "entrance_n")
local petalburg_woods_entrance_n_hub = DoorSlotHub("petalburg_woods", "entrance_n", petalburg_woods_entrance_n)
petalburg_woods_entrance_n:setHubIcon(petalburg_woods_entrance_n_hub)
local petalburg_woods_entrance_sw = DoorSlot("petalburg_woods", "entrance_sw")
local petalburg_woods_entrance_sw_hub = DoorSlotHub("petalburg_woods", "entrance_sw", petalburg_woods_entrance_sw)
petalburg_woods_entrance_sw:setHubIcon(petalburg_woods_entrance_sw_hub)
local petalburg_woods_entrance_se = DoorSlot("petalburg_woods", "entrance_se")
local petalburg_woods_entrance_se_hub = DoorSlotHub("petalburg_woods", "entrance_se", petalburg_woods_entrance_se)
petalburg_woods_entrance_se:setHubIcon(petalburg_woods_entrance_se_hub)