local petalburg_center = DoorSlot("petalburg", "center")
local petalburg_center_hub = DoorSlotHub("petalburg", "center", petalburg_center)
petalburg_center:setHubIcon(petalburg_center_hub)
local petalburg_mart = DoorSlot("petalburg", "mart")
local petalburg_mart_hub = DoorSlotHub("petalburg", "mart", petalburg_mart)
petalburg_mart:setHubIcon(petalburg_mart_hub)
local petalburg_gym = DoorSlot("petalburg", "gym")
local petalburg_gym_hub = DoorSlotHub("petalburg", "gym", petalburg_gym)
petalburg_gym:setHubIcon(petalburg_gym_hub)
local petalburg_house_se = DoorSlot("petalburg", "house_se")
local petalburg_house_se_hub = DoorSlotHub("petalburg", "house_se", petalburg_house_se)
petalburg_house_se:setHubIcon(petalburg_house_se_hub)
local petalburg_house_sw = DoorSlot("petalburg", "house_sw")
local petalburg_house_sw_hub = DoorSlotHub("petalburg", "house_sw", petalburg_house_sw)
petalburg_house_sw:setHubIcon(petalburg_house_sw_hub)
local petalburg_house_nw = DoorSlot("petalburg", "house_nw")
local petalburg_house_nw_hub = DoorSlotHub("petalburg", "house_nw", petalburg_house_nw)
petalburg_house_nw:setHubIcon(petalburg_house_nw_hub)