DoorSlot("route_104", "flower", DoorSlotHub("route_104", "flower"))
DoorSlot("route_104", "woods_n", DoorSlotHub("route_104", "woods_n"))
DoorSlot("route_104", "woods_sw", DoorSlotHub("route_104", "woods_sw"))
DoorSlot("route_104", "woods_se", DoorSlotHub("route_104", "woods_se"))
DoorSlot("route_104", "briney", DoorSlotHub("route_104", "briney"))