local rustboro_center = DoorSlot("rustboro", "center")
local rustboro_center_hub = DoorSlotHub("rustboro", "center", rustboro_center)
rustboro_center:setHubIcon(rustboro_center_hub)
local rustboro_mart = DoorSlot("rustboro", "mart")
local rustboro_mart_hub = DoorSlotHub("rustboro", "mart", rustboro_mart)
rustboro_mart:setHubIcon(rustboro_mart_hub)
local rustboro_gym = DoorSlot("rustboro", "gym")
local rustboro_gym_hub = DoorSlotHub("rustboro", "gym", rustboro_gym)
rustboro_gym:setHubIcon(rustboro_gym_hub)
local rustboro_school = DoorSlot("rustboro", "school")
local rustboro_school_hub = DoorSlotHub("rustboro", "school", rustboro_school)
rustboro_school:setHubIcon(rustboro_school_hub)
local rustboro_devon = DoorSlot("rustboro", "devon")
local rustboro_devon_hub = DoorSlotHub("rustboro", "devon", rustboro_devon)
rustboro_devon:setHubIcon(rustboro_devon_hub)
local rustboro_house_nw = DoorSlot("rustboro", "house_nw")
local rustboro_house_nw_hub = DoorSlotHub("rustboro", "house_nw", rustboro_house_nw)
rustboro_house_nw:setHubIcon(rustboro_house_nw_hub)
local rustboro_house_w = DoorSlot("rustboro", "house_w")
local rustboro_house_w_hub = DoorSlotHub("rustboro", "house_w", rustboro_house_w)
rustboro_house_w:setHubIcon(rustboro_house_w_hub)
local rustboro_house_sw = DoorSlot("rustboro", "house_sw")
local rustboro_house_sw_hub = DoorSlotHub("rustboro", "house_sw", rustboro_house_sw)
rustboro_house_sw:setHubIcon(rustboro_house_sw_hub)
local rustboro_house_ne = DoorSlot("rustboro", "house_ne")
local rustboro_house_ne_hub = DoorSlotHub("rustboro", "house_ne", rustboro_house_ne)
rustboro_house_ne:setHubIcon(rustboro_house_ne_hub)
local rustboro_house_e = DoorSlot("rustboro", "house_e")
local rustboro_house_e_hub = DoorSlotHub("rustboro", "house_e", rustboro_house_e)
rustboro_house_e:setHubIcon(rustboro_house_e_hub)
local rustboro_house_se = DoorSlot("rustboro", "house_se")
local rustboro_house_se_hub = DoorSlotHub("rustboro", "house_se", rustboro_house_se)
rustboro_house_se:setHubIcon(rustboro_house_se_hub)