local rusturf_tunnel_entrance_w = DoorSlot("rusturf_tunnel", "entrance_w")
local rusturf_tunnel_entrance_w_hub = DoorSlotHub("rusturf_tunnel", "entrance_w", rusturf_tunnel_entrance_w)
rusturf_tunnel_entrance_w:setHubIcon(rusturf_tunnel_entrance_w_hub)
local rusturf_tunnel_entrance_s = DoorSlot("rusturf_tunnel", "entrance_s")
local rusturf_tunnel_entrance_s_hub = DoorSlotHub("rusturf_tunnel", "entrance_s", rusturf_tunnel_entrance_s)
rusturf_tunnel_entrance_s:setHubIcon(rusturf_tunnel_entrance_s_hub)
local rusturf_tunnel_entrance_se = DoorSlot("rusturf_tunnel", "entrance_se")
local rusturf_tunnel_entrance_se_hub = DoorSlotHub("rusturf_tunnel", "entrance_se", rusturf_tunnel_entrance_se)
rusturf_tunnel_entrance_se:setHubIcon(rusturf_tunnel_entrance_se_hub)