local seafloor_cavern_room_1_sw = DoorSlot("seafloor_cavern", "room_1_sw")
local seafloor_cavern_room_1_sw_hub = DoorSlotHub("seafloor_cavern", "room_1_sw", seafloor_cavern_room_1_sw)
seafloor_cavern_room_1_sw:setHubIcon(seafloor_cavern_room_1_sw_hub)
local seafloor_cavern_room_1_se = DoorSlot("seafloor_cavern", "room_1_se")
local seafloor_cavern_room_1_se_hub = DoorSlotHub("seafloor_cavern", "room_1_se", seafloor_cavern_room_1_se)
seafloor_cavern_room_1_se:setHubIcon(seafloor_cavern_room_1_se_hub)
local seafloor_cavern_room_1_n = DoorSlot("seafloor_cavern", "room_1_n")
local seafloor_cavern_room_1_n_hub = DoorSlotHub("seafloor_cavern", "room_1_n", seafloor_cavern_room_1_n)
seafloor_cavern_room_1_n:setHubIcon(seafloor_cavern_room_1_n_hub)
local seafloor_cavern_room_2_n = DoorSlot("seafloor_cavern", "room_2_n")
local seafloor_cavern_room_2_n_hub = DoorSlotHub("seafloor_cavern", "room_2_n", seafloor_cavern_room_2_n)
seafloor_cavern_room_2_n:setHubIcon(seafloor_cavern_room_2_n_hub)
local seafloor_cavern_room_2_sw = DoorSlot("seafloor_cavern", "room_2_sw")
local seafloor_cavern_room_2_sw_hub = DoorSlotHub("seafloor_cavern", "room_2_sw", seafloor_cavern_room_2_sw)
seafloor_cavern_room_2_sw:setHubIcon(seafloor_cavern_room_2_sw_hub)
local seafloor_cavern_room_2_se = DoorSlot("seafloor_cavern", "room_2_se")
local seafloor_cavern_room_2_se_hub = DoorSlotHub("seafloor_cavern", "room_2_se", seafloor_cavern_room_2_se)
seafloor_cavern_room_2_se:setHubIcon(seafloor_cavern_room_2_se_hub)
local seafloor_cavern_room_3_nw = DoorSlot("seafloor_cavern", "room_3_nw")
local seafloor_cavern_room_3_nw_hub = DoorSlotHub("seafloor_cavern", "room_3_nw", seafloor_cavern_room_3_nw)
seafloor_cavern_room_3_nw:setHubIcon(seafloor_cavern_room_3_nw_hub)
local seafloor_cavern_room_3_ne = DoorSlot("seafloor_cavern", "room_3_ne")
local seafloor_cavern_room_3_ne_hub = DoorSlotHub("seafloor_cavern", "room_3_ne", seafloor_cavern_room_3_ne)
seafloor_cavern_room_3_ne:setHubIcon(seafloor_cavern_room_3_ne_hub)
local seafloor_cavern_room_3_c = DoorSlot("seafloor_cavern", "room_3_c")
local seafloor_cavern_room_3_c_hub = DoorSlotHub("seafloor_cavern", "room_3_c", seafloor_cavern_room_3_c)
seafloor_cavern_room_3_c:setHubIcon(seafloor_cavern_room_3_c_hub)
local seafloor_cavern_room_3_s = DoorSlot("seafloor_cavern", "room_3_s")
local seafloor_cavern_room_3_s_hub = DoorSlotHub("seafloor_cavern", "room_3_s", seafloor_cavern_room_3_s)
seafloor_cavern_room_3_s:setHubIcon(seafloor_cavern_room_3_s_hub)
local seafloor_cavern_room_4_nw = DoorSlot("seafloor_cavern", "room_4_nw")
local seafloor_cavern_room_4_nw_hub = DoorSlotHub("seafloor_cavern", "room_4_nw", seafloor_cavern_room_4_nw)
seafloor_cavern_room_4_nw:setHubIcon(seafloor_cavern_room_4_nw_hub)
local seafloor_cavern_room_4_ne = DoorSlot("seafloor_cavern", "room_4_ne")
local seafloor_cavern_room_4_ne_hub = DoorSlotHub("seafloor_cavern", "room_4_ne", seafloor_cavern_room_4_ne)
seafloor_cavern_room_4_ne:setHubIcon(seafloor_cavern_room_4_ne_hub)
local seafloor_cavern_room_4_sw = DoorSlot("seafloor_cavern", "room_4_sw")
local seafloor_cavern_room_4_sw_hub = DoorSlotHub("seafloor_cavern", "room_4_sw", seafloor_cavern_room_4_sw)
seafloor_cavern_room_4_sw:setHubIcon(seafloor_cavern_room_4_sw_hub)
local seafloor_cavern_room_4_se = DoorSlot("seafloor_cavern", "room_4_se")
local seafloor_cavern_room_4_se_hub = DoorSlotHub("seafloor_cavern", "room_4_se", seafloor_cavern_room_4_se)
seafloor_cavern_room_4_se:setHubIcon(seafloor_cavern_room_4_se_hub)
local seafloor_cavern_room_5_nw = DoorSlot("seafloor_cavern", "room_5_nw")
local seafloor_cavern_room_5_nw_hub = DoorSlotHub("seafloor_cavern", "room_5_nw", seafloor_cavern_room_5_nw)
seafloor_cavern_room_5_nw:setHubIcon(seafloor_cavern_room_5_nw_hub)
local seafloor_cavern_room_5_c = DoorSlot("seafloor_cavern", "room_5_c")
local seafloor_cavern_room_5_c_hub = DoorSlotHub("seafloor_cavern", "room_5_c", seafloor_cavern_room_5_c)
seafloor_cavern_room_5_c:setHubIcon(seafloor_cavern_room_5_c_hub)
local seafloor_cavern_room_5_s = DoorSlot("seafloor_cavern", "room_5_s")
local seafloor_cavern_room_5_s_hub = DoorSlotHub("seafloor_cavern", "room_5_s", seafloor_cavern_room_5_s)
seafloor_cavern_room_5_s:setHubIcon(seafloor_cavern_room_5_s_hub)
local seafloor_cavern_room_6_n = DoorSlot("seafloor_cavern", "room_6_n")
local seafloor_cavern_room_6_n_hub = DoorSlotHub("seafloor_cavern", "room_6_n", seafloor_cavern_room_6_n)
seafloor_cavern_room_6_n:setHubIcon(seafloor_cavern_room_6_n_hub)
local seafloor_cavern_room_6_sw = DoorSlot("seafloor_cavern", "room_6_sw")
local seafloor_cavern_room_6_sw_hub = DoorSlotHub("seafloor_cavern", "room_6_sw", seafloor_cavern_room_6_sw)
seafloor_cavern_room_6_sw:setHubIcon(seafloor_cavern_room_6_sw_hub)
local seafloor_cavern_room_6_se = DoorSlot("seafloor_cavern", "room_6_se")
local seafloor_cavern_room_6_se_hub = DoorSlotHub("seafloor_cavern", "room_6_se", seafloor_cavern_room_6_se)
seafloor_cavern_room_6_se:setHubIcon(seafloor_cavern_room_6_se_hub)