local sky_pillar_entrance = DoorSlot("sky_pillar", "entrance")
local sky_pillar_entrance_hub = DoorSlotHub("sky_pillar", "entrance", sky_pillar_entrance)
sky_pillar_entrance:setHubIcon(sky_pillar_entrance_hub)
local sky_pillar_1f_entrance = DoorSlot("sky_pillar", "1f_entrance")
local sky_pillar_1f_entrance_hub = DoorSlotHub("sky_pillar", "1f_entrance", sky_pillar_1f_entrance)
sky_pillar_1f_entrance:setHubIcon(sky_pillar_1f_entrance_hub)
local sky_pillar_1f_stairs = DoorSlot("sky_pillar", "1f_stairs")
local sky_pillar_1f_stairs_hub = DoorSlotHub("sky_pillar", "1f_stairs", sky_pillar_1f_stairs)
sky_pillar_1f_stairs:setHubIcon(sky_pillar_1f_stairs_hub)
local sky_pillar_2f_stairs_nw = DoorSlot("sky_pillar", "2f_stairs_nw")
local sky_pillar_2f_stairs_nw_hub = DoorSlotHub("sky_pillar", "2f_stairs_nw", sky_pillar_2f_stairs_nw)
sky_pillar_2f_stairs_nw:setHubIcon(sky_pillar_2f_stairs_nw_hub)
local sky_pillar_2f_stairs_ne = DoorSlot("sky_pillar", "2f_stairs_ne")
local sky_pillar_2f_stairs_ne_hub = DoorSlotHub("sky_pillar", "2f_stairs_ne", sky_pillar_2f_stairs_ne)
sky_pillar_2f_stairs_ne:setHubIcon(sky_pillar_2f_stairs_ne_hub)
local sky_pillar_3f_stairs_nw = DoorSlot("sky_pillar", "3f_stairs_nw")
local sky_pillar_3f_stairs_nw_hub = DoorSlotHub("sky_pillar", "3f_stairs_nw", sky_pillar_3f_stairs_nw)
sky_pillar_3f_stairs_nw:setHubIcon(sky_pillar_3f_stairs_nw_hub)
local sky_pillar_3f_stairs_n = DoorSlot("sky_pillar", "3f_stairs_n")
local sky_pillar_3f_stairs_n_hub = DoorSlotHub("sky_pillar", "3f_stairs_n", sky_pillar_3f_stairs_n)
sky_pillar_3f_stairs_n:setHubIcon(sky_pillar_3f_stairs_n_hub)
local sky_pillar_3f_stairs_ne = DoorSlot("sky_pillar", "3f_stairs_ne")
local sky_pillar_3f_stairs_ne_hub = DoorSlotHub("sky_pillar", "3f_stairs_ne", sky_pillar_3f_stairs_ne)
sky_pillar_3f_stairs_ne:setHubIcon(sky_pillar_3f_stairs_ne_hub)
local sky_pillar_4f_stairs_nw = DoorSlot("sky_pillar", "4f_stairs_nw")
local sky_pillar_4f_stairs_nw_hub = DoorSlotHub("sky_pillar", "4f_stairs_nw", sky_pillar_4f_stairs_nw)
sky_pillar_4f_stairs_nw:setHubIcon(sky_pillar_4f_stairs_nw_hub)
local sky_pillar_4f_stairs_n = DoorSlot("sky_pillar", "4f_stairs_n")
local sky_pillar_4f_stairs_n_hub = DoorSlotHub("sky_pillar", "4f_stairs_n", sky_pillar_4f_stairs_n)
sky_pillar_4f_stairs_n:setHubIcon(sky_pillar_4f_stairs_n_hub)
local sky_pillar_4f_stairs_ne = DoorSlot("sky_pillar", "4f_stairs_ne")
local sky_pillar_4f_stairs_ne_hub = DoorSlotHub("sky_pillar", "4f_stairs_ne", sky_pillar_4f_stairs_ne)
sky_pillar_4f_stairs_ne:setHubIcon(sky_pillar_4f_stairs_ne_hub)