local slateport_center = DoorSlot("slateport", "center")
local slateport_center_hub = DoorSlotHub("slateport", "center", slateport_center)
slateport_center:setHubIcon(slateport_center_hub)
local slateport_house_s = DoorSlot("slateport", "house_s")
local slateport_house_s_hub = DoorSlotHub("slateport", "house_s", slateport_house_s)
slateport_house_s:setHubIcon(slateport_house_s_hub)
local slateport_house_w = DoorSlot("slateport", "house_w")
local slateport_house_w_hub = DoorSlotHub("slateport", "house_w", slateport_house_w)
slateport_house_w:setHubIcon(slateport_house_w_hub)
local slateport_mart = DoorSlot("slateport", "mart")
local slateport_mart_hub = DoorSlotHub("slateport", "mart", slateport_mart)
slateport_mart:setHubIcon(slateport_mart_hub)
local slateport_museum = DoorSlot("slateport", "museum")
local slateport_museum_hub = DoorSlotHub("slateport", "museum", slateport_museum)
slateport_museum:setHubIcon(slateport_museum_hub)
local slateport_contest = DoorSlot("slateport", "contest")
local slateport_contest_hub = DoorSlotHub("slateport", "contest", slateport_contest)
slateport_contest:setHubIcon(slateport_contest_hub)
local slateport_fan_club = DoorSlot("slateport", "fan_club")
local slateport_fan_club_hub = DoorSlotHub("slateport", "fan_club", slateport_fan_club)
slateport_fan_club:setHubIcon(slateport_fan_club_hub)
local slateport_stern = DoorSlot("slateport", "stern")
local slateport_stern_hub = DoorSlotHub("slateport", "stern", slateport_stern)
slateport_stern:setHubIcon(slateport_stern_hub)