DoorSlot("slateport", "center", DoorSlotHub("slateport", "center"))
DoorSlot("slateport", "house_s", DoorSlotHub("slateport", "house_s"))
DoorSlot("slateport", "house_w", DoorSlotHub("slateport", "house_w"))
DoorSlot("slateport", "mart", DoorSlotHub("slateport", "mart"))
DoorSlot("slateport", "museum", DoorSlotHub("slateport", "museum"))
DoorSlot("slateport", "contest", DoorSlotHub("slateport", "contest"))
DoorSlot("slateport", "fan_club", DoorSlotHub("slateport", "fan_club"))
DoorSlot("slateport", "stern", DoorSlotHub("slateport", "stern"))