local sootopolis_center = DoorSlot("sootopolis", "center")
local sootopolis_center_hub = DoorSlotHub("sootopolis", "center", sootopolis_center)
sootopolis_center:setHubIcon(sootopolis_center_hub)
local sootopolis_house_w1 = DoorSlot("sootopolis", "house_w1")
local sootopolis_house_w1_hub = DoorSlotHub("sootopolis", "house_w1", sootopolis_house_w1)
sootopolis_house_w1:setHubIcon(sootopolis_house_w1_hub)
local sootopolis_house_w2 = DoorSlot("sootopolis", "house_w2")
local sootopolis_house_w2_hub = DoorSlotHub("sootopolis", "house_w2", sootopolis_house_w2)
sootopolis_house_w2:setHubIcon(sootopolis_house_w2_hub)
local sootopolis_house_w3 = DoorSlot("sootopolis", "house_w3")
local sootopolis_house_w3_hub = DoorSlotHub("sootopolis", "house_w3", sootopolis_house_w3)
sootopolis_house_w3:setHubIcon(sootopolis_house_w3_hub)
local sootopolis_house_w4 = DoorSlot("sootopolis", "house_w4")
local sootopolis_house_w4_hub = DoorSlotHub("sootopolis", "house_w4", sootopolis_house_w4)
sootopolis_house_w4:setHubIcon(sootopolis_house_w4_hub)
local sootopolis_house_e1 = DoorSlot("sootopolis", "house_e1")
local sootopolis_house_e1_hub = DoorSlotHub("sootopolis", "house_e1", sootopolis_house_e1)
sootopolis_house_e1:setHubIcon(sootopolis_house_e1_hub)
local sootopolis_house_e2 = DoorSlot("sootopolis", "house_e2")
local sootopolis_house_e2_hub = DoorSlotHub("sootopolis", "house_e2", sootopolis_house_e2)
sootopolis_house_e2:setHubIcon(sootopolis_house_e2_hub)
local sootopolis_house_e3 = DoorSlot("sootopolis", "house_e3")
local sootopolis_house_e3_hub = DoorSlotHub("sootopolis", "house_e3", sootopolis_house_e3)
sootopolis_house_e3:setHubIcon(sootopolis_house_e3_hub)
local sootopolis_house_e4 = DoorSlot("sootopolis", "house_e4")
local sootopolis_house_e4_hub = DoorSlotHub("sootopolis", "house_e4", sootopolis_house_e4)
sootopolis_house_e4:setHubIcon(sootopolis_house_e4_hub)
local sootopolis_house_e5 = DoorSlot("sootopolis", "house_e5")
local sootopolis_house_e5_hub = DoorSlotHub("sootopolis", "house_e5", sootopolis_house_e5)
sootopolis_house_e5:setHubIcon(sootopolis_house_e5_hub)
local sootopolis_mart = DoorSlot("sootopolis", "mart")
local sootopolis_mart_hub = DoorSlotHub("sootopolis", "mart", sootopolis_mart)
sootopolis_mart:setHubIcon(sootopolis_mart_hub)
local sootopolis_gym = DoorSlot("sootopolis", "gym")
local sootopolis_gym_hub = DoorSlotHub("sootopolis", "gym", sootopolis_gym)
sootopolis_gym:setHubIcon(sootopolis_gym_hub)
local sootopolis_dive = DoorSlot("sootopolis", "dive")
local sootopolis_dive_hub = DoorSlotHub("sootopolis", "dive", sootopolis_dive)
sootopolis_dive:setHubIcon(sootopolis_dive_hub)