local verdanturf_center = DoorSlot("verdanturf", "center")
local verdanturf_center_hub = DoorSlotHub("verdanturf", "center", verdanturf_center)
verdanturf_center:setHubIcon(verdanturf_center_hub)
local verdanturf_house_sw = DoorSlot("verdanturf", "house_sw")
local verdanturf_house_sw_hub = DoorSlotHub("verdanturf", "house_sw", verdanturf_house_sw)
verdanturf_house_sw:setHubIcon(verdanturf_house_sw_hub)
local verdanturf_house_s = DoorSlot("verdanturf", "house_s")
local verdanturf_house_s_hub = DoorSlotHub("verdanturf", "house_s", verdanturf_house_s)
verdanturf_house_s:setHubIcon(verdanturf_house_s_hub)
local verdanturf_house_se = DoorSlot("verdanturf", "house_se")
local verdanturf_house_se_hub = DoorSlotHub("verdanturf", "house_se", verdanturf_house_se)
verdanturf_house_se:setHubIcon(verdanturf_house_se_hub)
local verdanturf_mart = DoorSlot("verdanturf", "mart")
local verdanturf_mart_hub = DoorSlotHub("verdanturf", "mart", verdanturf_mart)
verdanturf_mart:setHubIcon(verdanturf_mart_hub)
local verdanturf_contest = DoorSlot("verdanturf", "contest")
local verdanturf_contest_hub = DoorSlotHub("verdanturf", "contest", verdanturf_contest)
verdanturf_contest:setHubIcon(verdanturf_contest_hub)
local verdanturf_tunnel = DoorSlot("verdanturf", "tunnel")
local verdanturf_tunnel_hub = DoorSlotHub("verdanturf", "tunnel", verdanturf_tunnel)
verdanturf_tunnel:setHubIcon(verdanturf_tunnel_hub)