local victory_road_b1f_s_ladder_sw = DoorSlot("victory_road", "b1f_s_ladder_sw")
local victory_road_b1f_s_ladder_sw_hub = DoorSlotHub("victory_road", "b1f_s_ladder_sw", victory_road_b1f_s_ladder_sw)
victory_road_b1f_s_ladder_sw:setHubIcon(victory_road_b1f_s_ladder_sw_hub)
local victory_road_b1f_s_ladder_e = DoorSlot("victory_road", "b1f_s_ladder_e")
local victory_road_b1f_s_ladder_e_hub = DoorSlotHub("victory_road", "b1f_s_ladder_e", victory_road_b1f_s_ladder_e)
victory_road_b1f_s_ladder_e:setHubIcon(victory_road_b1f_s_ladder_e_hub)
local victory_road_b1f_s_ladder_ne = DoorSlot("victory_road", "b1f_s_ladder_ne")
local victory_road_b1f_s_ladder_ne_hub = DoorSlotHub("victory_road", "b1f_s_ladder_ne", victory_road_b1f_s_ladder_ne)
victory_road_b1f_s_ladder_ne:setHubIcon(victory_road_b1f_s_ladder_ne_hub)
local victory_road_b1f_n_ladder_nw = DoorSlot("victory_road", "b1f_n_ladder_nw")
local victory_road_b1f_n_ladder_nw_hub = DoorSlotHub("victory_road", "b1f_n_ladder_nw", victory_road_b1f_n_ladder_nw)
victory_road_b1f_n_ladder_nw:setHubIcon(victory_road_b1f_n_ladder_nw_hub)
local victory_road_b1f_n_ladder_sw = DoorSlot("victory_road", "b1f_n_ladder_sw")
local victory_road_b1f_n_ladder_sw_hub = DoorSlotHub("victory_road", "b1f_n_ladder_sw", victory_road_b1f_n_ladder_sw)
victory_road_b1f_n_ladder_sw:setHubIcon(victory_road_b1f_n_ladder_sw_hub)
local victory_road_b1f_n_ladder_se = DoorSlot("victory_road", "b1f_n_ladder_se")
local victory_road_b1f_n_ladder_se_hub = DoorSlotHub("victory_road", "b1f_n_ladder_se", victory_road_b1f_n_ladder_se)
victory_road_b1f_n_ladder_se:setHubIcon(victory_road_b1f_n_ladder_se_hub)
local victory_road_b2f_ladder_sw = DoorSlot("victory_road", "b2f_ladder_sw")
local victory_road_b2f_ladder_sw_hub = DoorSlotHub("victory_road", "b2f_ladder_sw", victory_road_b2f_ladder_sw)
victory_road_b2f_ladder_sw:setHubIcon(victory_road_b2f_ladder_sw_hub)
local victory_road_b2f_ladder_se = DoorSlot("victory_road", "b2f_ladder_se")
local victory_road_b2f_ladder_se_hub = DoorSlotHub("victory_road", "b2f_ladder_se", victory_road_b2f_ladder_se)
victory_road_b2f_ladder_se:setHubIcon(victory_road_b2f_ladder_se_hub)
local victory_road_b2f_ladder_c = DoorSlot("victory_road", "b2f_ladder_c")
local victory_road_b2f_ladder_c_hub = DoorSlotHub("victory_road", "b2f_ladder_c", victory_road_b2f_ladder_c)
victory_road_b2f_ladder_c:setHubIcon(victory_road_b2f_ladder_c_hub)
local victory_road_b2f_ladder_ne = DoorSlot("victory_road", "b2f_ladder_ne")
local victory_road_b2f_ladder_ne_hub = DoorSlotHub("victory_road", "b2f_ladder_ne", victory_road_b2f_ladder_ne)
victory_road_b2f_ladder_ne:setHubIcon(victory_road_b2f_ladder_ne_hub)